### ISSUE TITLE
Create presentation

### ISSUE THREAD

**Issue by RyazMax** [vovac12/ecology#1]
# We need to create presentation 
## information message about current state of some natural object of some subject of Russian Federation

It probably should contain next parts:

* Basic info about subject with map of chosen subject #5 
* Main part
  * State of object
  * Trends 
  * Main sources of pollution
* Some negative factor that affects badly on people (1-2 slides) #7 
* Conclusion with supposed steps to improve ecological situation #6 
* Bibliography

Full info can find [there](https://github.com/vovac12/ecology/files/4787844/trebovania_k_prezentatsii.pdf)

**Comment by vovac12** [comment]
Too abstract...
